daemon: Remove unusable ripple for Blade Early 2020/2021 Base
These devices don't have a matrix (custom effect) set up, which is
required for the ripple effect.

The effect is non-functional via the Python library:
AttributeError: 'NoneType' object has no attribute 'setRipple'

See also:
84247866d28f9d1ba1b2dacf94ef4b6aa175a935
5562e0810e2e994d67ae77e12194f2fcc7a99a0e