daemon: only add files ending in .py to the module import list
vim creates .foo.py.swp files while a file is open which causes the daemon to
fail with confusing error messages:
ModuleNotFoundError: No module named 'openrazer_daemon.hardware.'